line.bot:
  channel-token: 'Xv/I7p0MXs6/+IdQJON4RbD26rOd0QQpBv4GvpiSPwR+KoqTFQk41DmX/iYf2EUFJvZtFHNw2yc00srk31QRwzTXizlrdkfeYBxXX27G3CV3uVeH+gnzImj89IV7Ruf6ukn2rd6vU5E3FEQAs7nj4gdB04t89/1O/w1cDnyilFU='
  channel-secret: '4c3ae49617a1903ea05763971fc5d541'
  handler.path: /callback

# create branch develop